Game 제작을 위한 기본적인 인터페이스 및 샘플 게임 제작
Perlmint/sandwich pull request #15
Opened 2021-01-27 05:55 UTC by jaeyounglee978

Config에 game 관련 선언(어디서 명령어를 받을 것인지, 어느 채널을 게임이 바라볼 대상으로 선택할 것인지)

1. main.ts에서 게임 init. class에 readonly 필드로 게임 이름을 선언해놓고 config에 해당 게임 이름이 선언되어 있을 때만 init
2. 게임 초기화

~놀랍게도 테스트를 아직 안했다고 한다.~ 일단 구조 검증 부탁드림니다.

2021-01-27 06:03 UTC, Perlmint commented
https://stackoverflow.com/questions/54165756/eslint-glob-is-not-considering-all-directories-recursively 참고해서 package.json의 scripts/lint 수정 필요

2021-01-28 04:09 UTC, Perlmint requested changes
from채널들에서 말한 횟수를 카운트 해서 특정 명령을 target채널에서 치면 통계를 보여주는 것이 맞는지?

2021-01-28 04:09 UTC, Perlmint commented on src/game/GuwaaGame.ts
> +    const entries = [...result.entries()].map(function (v) { return v[1][1] })
[iter-tools](https://www.npmjs.com/package/iter-tools)를 쓰면 배열로 안만들고 바로 map적용할 수 있을 것 같음
iterator에서 바로 정렬하는 것 도 있으니까 잘 활용하면 좋을 듯?

2021-01-28 04:09 UTC, Perlmint commented on src/game/GuwaaGame.ts
> +        if (event.channelId == cId)
끄아악 {} 생략은 죄악이다!

2021-01-28 04:25 UTC, jaeyounglee978 commented
> from채널들에서 말한 횟수를 카운트 해서 특정 명령을 target채널에서 치면 통계를 보여주는 것이 맞는지?

이해하신 바가 맞습니다.

2021-01-28 04:26 UTC, jaeyounglee978 commented on src/game/gamify.ts
> +export function makeGameObj(g: GameConstructable, commandFrom: [Remote, string][], messageTarget: [Remote, string][], command: string) {
이게 이렇게 빙빙 돌아가는 방법을 쓴게, 바로 new 호출이 안되더라구요. 혹시 방법을 알고 계시다면 조언을 부탁드립니다...

2021-01-28 04:26 UTC, jaeyounglee978 commented on src/game/GuwaaGame.ts
> +    return command === message;
어 그러네요 여기 왜 이렇게 했지. 수정하겠습니다.

2021-01-28 04:32 UTC, jaeyounglee978 commented on src/game/GuwaaGame.ts
> +    this.initRemoteCommandEventHander();
수정 완료

2021-01-28 04:32 UTC, jaeyounglee978 commented on src/discord.ts
> +  public async sendMessageDefault(channelName: string, message: string): Promise<void> {
AsBot으로 변경했습니다. 이 편이 더 명확하네요 감사함니다.

2021-01-28 04:32 UTC, jaeyounglee978 commented on src/game/gamify.ts
> +  let map = new Map();
const 로 수정 완료

2021-01-28 04:35 UTC, jaeyounglee978 commented on src/game/GuwaaGame.ts
> +    this.from = from;
아래와 같이 수정해봤는데, Game interface에서 선언한 필드를 GuwaaGame에서 선언해주지 않았다고 에러가 발생하네요. 이 경우 어떻게 해야하나요?

```
public constructor(from: [Remote, string][], private messageTarget: [Remote, string][], private command: string) {
    // this.from = from;
    // this.messageTarget = messageTarget;
    // this.command = command;
}
```

2021-01-28 04:54 UTC, Perlmint commented
> > from채널들에서 말한 횟수를 카운트 해서 특정 명령을 target채널에서 치면 통계를 보여주는 것이 맞는지?
> 
> 이해하신 바가 맞습니다.

굳이 나눌 필요가 있나 싶은데 명확한 기획이 없으니 구현자 맘대로

2021-01-28 04:56 UTC, Perlmint commented on src/game/GuwaaGame.ts
> +    this.from = from;
인터페이스에 정의 되어있으면 그건 public으로 노출이 되어야 함.

2021-01-28 04:58 UTC, Perlmint commented on src/game/gamify.ts
> +export function makeGameObj(g: GameConstructable, commandFrom: [Remote, string][], messageTarget: [Remote, string][], command: string) {
음... 혹시 get으로 얻어서 변수에 넣고 null체크 후에 해봄?
에러도 적어주면 원인 고민해보기에 좋을 듯

2021-01-28 05:09 UTC, jaeyounglee978 commented on src/game/gamify.ts
> +export function makeGameObj(g: GameConstructable, commandFrom: [Remote, string][], messageTarget: [Remote, string][], command: string) {
아 제가 말했던건 Game -> GameConstructor  구조가 생기기 전에, 그냥 new Game 이런 식으로 했을 때의 에러였습니다. 지금은 되네요. 불필요한 메서드 같으니  makeGameObj는 삭제하겠습니다.

2021-01-28 14:39 UTC, Perlmint commented on src/game/GuwaaGame.ts
> +      prevCounter[1] = ++prevCounter[1]
아니 그래서 이건 왜 냅두는거야...?

2021-02-02 12:04 UTC, Perlmint requested changes
사소한 것들 수정하고 마무리 지읍시다

2021-02-02 12:04 UTC, Perlmint commented on src/game/GuwaaGame.ts
> +        console.log(this.guwaaCounterMap.get(event.userId));
이미 prevCounter라고 가져왔으니 그걸 씁시다.

2021-02-02 13:51 UTC, jaeyounglee978 commented on src/game/GuwaaGame.ts
> +    this.guwaaCounterMap = new Map()
헐 lint가 안잡아줬어요, 수정하겠습니다.

2021-02-02 14:00 UTC, jaeyounglee978 commented on src/game/GuwaaGame.ts
> +        console.log(this.guwaaCounterMap.get(event.userId));
이거 테스트용 로그였는데 그냥 제거하겠습니다.

2021-02-02 14:38 UTC, Perlmint approved these changes

2021-02-03 06:20 UTC, merged